### ISSUE TITLE
Can't activate

### ISSUE THREAD

**Issue by pickleton89** [bwydoogh/obsidian-force-view-mode-of-note#1]
I downloaded the zip package and unzipped to its folder. Put the folder int he /.obsidian/plugins. Reload Obsidian and see the plugin in the community plugin list. Tried to activate plugin and throws an error.  Looked in developer console and found this error. Which is confusing as a see the plugin folder there. 

Plugin failure: obsidian-view-mode-by-frontmatter Error: ENOENT: no such file or directory, open '/Users/kiefer/Documents/Obsidian/Personal_Vault/.obsidian/plugins/obsidian-force-view-mode-of-note-1.0.0/main.js'

I did notice in the plugin in folder the main file had a .ts extension not a .js extension. I changed that to main.js and it didn't work. This was the error in console:

Plugin failure: obsidian-view-mode-by-frontmatter SyntaxError: Cannot use import statement outside a module
    at eval (<anonymous>)
    at app.js:1
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)

**Comment by pickleton89** [comment]
I fixed it. Found that I only needed to add the main.js and manifest.json files to folder in plugins.

**Comment by ackstorm23** [comment]
I have this problem too, but I don't understand what you did to fix it @pickleton89 ?

**Comment by pickleton89** [comment]
@ackstorm23 on the git-hub landing page. Off to the side you will see a 'Releases' button, click to navigate to that page. You will find the main.js and manifest.json files to download there. Put them in your /.obsidian/plugins folder under a folder named for this plugin. Then it will load, however, the plugin isn't working for me. The front matter is recognized as front matter, but doesn't open notes in the listed view. So still broke for me.

**Comment by ackstorm23** [comment]
@pickleton89 check out my issue on the frontmatter problem :)
