### ISSUE TITLE
Opening new pan with Ctrl/Cmd + Click on internal link set original page to source mode

### ISSUE THREAD

**Issue by Write** [bwydoogh/obsidian-force-view-mode-of-note#12]
Even if the page linked to doesn't have an obsidianUIMode attribute set, it'll set the original page (where we clicked the internal link to open the new pane with Ctrl + click) to source mode. Disabling the plugin instantly solve the issue.

**Comment by bwydoogh** [comment]
I believe this behavior will be possible to turn off with https://github.com/bwydoogh/obsidian-force-view-mode-of-note/issues/4.

**Comment by bwydoogh** [comment]
See new setting released in `1.0.3`; turning that setting ON should prevent forcing view mode on opened notes.
