### ISSUE TITLE
preview mode forcing to edit mode in multi-pane focus

### ISSUE THREAD

**Issue by chaseadamsio** [bwydoogh/obsidian-force-view-mode-of-note#13]
I noticed today that while working in multi-pane if one file was in preview and one file was in edit and I focused on the preview file, it would force it into edit mode.

I disabled this plugin and found that everything worked as expected, here's a loom: https://www.loom.com/share/8dabcd3628a348188511f0d555cb007b

Is it possible that this is a multi-pane issue?

**Comment by bwydoogh** [comment]
Did you try the setting "Ignore opened files" (which should not force opened files to their default editor mode)?

**Comment by chaseadamsio** [comment]
Thanks for the quick response @bwydoogh! I couldn't find any settings for the plugin and it turned out i was on an older version of the plugin. I uninstalled it and installed the "Force note view mode" and sure enough there was a settings panel that has that option.

I'm all set, thank you!
