### ISSUE TITLE
[Bug] Changing focused tab reloads the preset view

### ISSUE THREAD

**Issue by Armagedoom** [bwydoogh/obsidian-force-view-mode-of-note#14]
**Steps to reproduce:**
* Open two tabs
* In one of them, load a note that has the variable defined `obsidianUIMode: preview` and change the view manually
* Select the second tab, then go back to the note with the variable. It will automatically change view back to the defined in the variable `obsidianUIMode: preview` as if you had just oppened the file.

**Expected behavior:**
It should keep its current view when we are switching back and forth to it, and only have the forced view defined in the variable when we just oppened the file.

Thank you **so much** for this plugin!

**Comment by bwydoogh** [comment]
Hi. Can you have a look at https://github.com/bwydoogh/obsidian-force-view-mode-of-note/issues/13? Seems like the same behaviour you are noticing (and which you can disable using a setting).
Please let me know.

**Comment by Armagedoom** [comment]
Sorry for that, yes, this fixes the issue.
I think it should be the default behaviour shouldn't it?
Anyhow, thank you again for this :)
