### ISSUE TITLE
Allow switching based on tags/file names or other rules

### ISSUE THREAD

**Issue by tomzorz** [bwydoogh/obsidian-force-view-mode-of-note#18]
Hi!

Could we have an option in the settings to define a search term (so we have tags, paths etc...) and force the view mode based on that? E.g. `#moc` or `#overview` in a note could trigger the switch.

Thanks!

**Comment by twiddli** [comment]
Not quite it, but I added something similar, see #33

**Comment by KillWolfVlad** [comment]
Add ability to use file name patterns in PR #35, you can build branch by yourself and use feature already now.

**Comment by bwydoogh** [comment]
Possible to switch based on file names: since `1.2.2`
Thanks @KillWolfVlad.
