### ISSUE TITLE
Add an option for debounce

### ISSUE THREAD

**Issue by chenyukang** [bwydoogh/obsidian-force-view-mode-of-note#19]
Could we add an option for the debounce?
I'd like to use smaller number for this 😁

**Comment by bwydoogh** [comment]
Will add an option; but not without risk: can interfere with other plug-ins (or core behavior) when set too low.

**Comment by bwydoogh** [comment]
FYI: set to 300 ms (was 500 ms) in `1.1.1`; a setting is still on my TO DO list ;-)

**Comment by bwydoogh** [comment]
Released `1.2.1`; thanks @KillWolfVlad
