### ISSUE TITLE
Does not take effect

### ISSUE THREAD

**Issue by ackstorm23** [bwydoogh/obsidian-force-view-mode-of-note#2]
I have tried the following code in several notes, but they still open in source mode. 

```
---
obsidianUIMode: preview
---
```

The plugin enabled without error.  Is there a version of obsidian I need to have for this to work?

**Comment by ackstorm23** [comment]
The git readme says ```obsidianUIMode``` but the plugin says it should be ```obsidian_ui_mode```

It works with the latter.

**Comment by pickleton89** [comment]
Thanks @ackstorm23. That underscore version works on my end now also. Thanks

**Comment by pickleton89** [comment]
@ackstorm23  The files from the Release are 6 days old. The is a committ on removing the underscores. Looks like update files haven't been pushed to release.

**Comment by bwydoogh** [comment]
> @ackstorm23 The files from the Release are 6 days old. The is a committ on removing the underscores. Looks like update files haven't been pushed to release.

Hi @pickleton89 , @ackstorm23.
True; forgot to push new build (after dealing with review remarks from Obsidian devs); done now.
