### ISSUE TITLE
FR: Force Live Preview / Source Mode

### ISSUE THREAD

**Issue by chrisgrieser** [bwydoogh/obsidian-force-view-mode-of-note#21]
with the new version 0.13.14, there are basically 3 modes, so it could be useful to force live preview / source mode as well!

**Comment by zhl111** [comment]
Looking forward to adding new features

**Comment by Superfeuchter** [comment]
I would appreciate this, too.

**Comment by bwydoogh** [comment]
In `1.1.0` version - released today - a new front matter key `ObsidianEditingMode` can be used (with this plug-in): "live" will force the "Live Preview" mode; the alternative is "source". 

Both keys, `ObsidianUIMode` and `ObsidianEditingMode`, can be used together at the same time.

**Comment by chrisgrieser** [comment]
fantastic, thank you!

minor follow-up: wouldn't it be a bit simpler to have only one frontmatter key `obsidianUIMode`, which can have 3 different valid values? The solution with two frontmatter keys was a bit confusing to me at first

**Comment by bwydoogh** [comment]
I understand your comment. However, here I chose to follow Obsidian's logic completely: on the one hand there is the UI mode and on the other hand there is the editing mode (both in the API and in Obsidian's settings). Hopefully this will not be perceived as too cumbersome 🤞.

**Comment by Superfeuchter** [comment]
Thanks for the new version!
