### ISSUE TITLE
Instant view mode switch, losing highlight

### ISSUE THREAD

**Issue by dima-stefantsov** [bwydoogh/obsidian-force-view-mode-of-note#22]
Hi.
1. I am on default page with default plain text edit mode.
2. I click on a link, new page with "obsidianUIMode: preview" opens in edit mode first, then after some time it switches to read mode.
3. When I click a link that leads away from current forced-viewmode page, it first renders as read mode, then after some time switches back to what it's supposed to be: plain text edit.

I can see two issues here:
1. I'd like this to be instant, not with delay, the moment content is drawn it should be already in specified view mode.
2. Highlight that was shining on initial load is lost after the mode switch, so after going through link I'm lost on the page.

Is it something that you can not overcome? Can you only start reading new page frontmatter only after page was already rendered, so you can not change view mode before it was loaded and displayed? Then there maybe a way to overcome it by using custom link format in parent page instead of relying on frontmatter?

Your plugin does exactly what I want, but with this two issues it's more comfortable for me to manually switch modes. Is there a way to improve it somehow?

**Comment by bwydoogh** [comment]
Hi. There is a reason for this: Obsidian does stuff when opening a new pane (f.e. it collapses headers, lists, …). If the plug-in wouldn't "wait", there would be a conflict between the plug-in (= switch from view mode) and Obsidian (collapsing headers, lists, …). Initially, there was no delay and this was the reason of many issues with that behavior.
