### ISSUE TITLE
Idea: create preview_readonly (or preview_no_edit) option, so the button "Click to edit" is not available

### ISSUE THREAD

**Issue by agnoldo** [bwydoogh/obsidian-force-view-mode-of-note#23]
First of all, many thanks for this great plugin, that I have been using for a long time in Obsidian!

Now to the idea: with this new mode, it would be possible to create readonly pages, suitable for end-users that should not be allowed to edit source code. Imagine that I create a home page with some buttons that open templates to create new notes. The home page itself should not be editable and should come in preview mode by default. So a "preview_no_edit" or "preview_readonly" mode would be amazing!

**Comment by bwydoogh** [comment]
I've been thinking about this for a while. Very interesting idea but I don't see this within the scope of this plug-in. Your suggestion goes in the direction of "who-may-do-what" on a note. This involves a lot of cases and creates an extra complexity (I have to make sure that a note cannot be edited in any way; not even through other plugins (think of plugins that can edit a note by adding text: MetaEdit, Review, Note Refactor, text transporter, ...)).

Still, interesting idea and maybe post this suggestion in Obsidian's forum as a feature request.
