### ISSUE TITLE
[BUG] Overrides my default editing mode.

### ISSUE THREAD

**Issue by cjolson** [bwydoogh/obsidian-force-view-mode-of-note#26]
I wanted this plugin to always open specific notes in preview mode (while allowing most notes to open in edit mode by default).  After installing and adding the YAML below to some notes, all of the notes in my vault – except for those I specified to open in Preview mode using this plugin – now open in Source mode instead of Live Preview mode. Even those which don't have any YAML.
```
---
obsidianUIMode: preview
---
```

#### Expected Behavior
Unless I specify the edit mode to be different in the YAML, all notes would still use Live Preview for the editing mode.

**Comment by cjolson** [comment]
Actually, never mind. I installed and rebooted, and now I think it might be fine. Or maybe I was looking at notes that were poor examples before.

**Comment by bwydoogh** [comment]
OK, thanks for the update. I can't reproduce this myself. Should you still have the problem again please feel free to register and I will check.
