### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by richardlm** [bwydoogh/obsidian-force-view-mode-of-note#3]
I have followed the instructions and noted the learnings from the closed issues, but this still does not work for me.

- I have downloaded main.js and manifest.js to the folder:
   - vault/.obsidian/plugins/obsidian-force-view-mode-of-note
- I reloaded Obsidian
- I enabled the plugin in the 'Community plugins' page (version 1.0.0)
- I added these three lines to the start of a few files:
   \---
   obsidian_ui_mode: preview
   \---

None of them open in preview mode - they all open in source mode.

I don't know what else I can do to diagnose the problem.

**Comment by bwydoogh** [comment]
Hello. You should use `obsidianUIMode: preview`. Can you give it a try?

**Comment by richardlm** [comment]
Yes, that works - many thanks.
