### ISSUE TITLE
Support setting view mode only when open the note in a new pane for the first time

### ISSUE THREAD

**Issue by wenlzhang** [bwydoogh/obsidian-force-view-mode-of-note#4]
This feature request may suit the following use case:

1. Sometimes, one opens a note, Note A, in a new pane for the first time and would like it to be in preview mode by default.
2. Then one realizes that this note needs to be edited. For this, one can switch to edit mode and make some changes.
3. After editing Note A, one goes to view/edit another note, Note B, in another pane.
4. After viewing/editing Note B, one wants to go back to Note A in edit mode to make further changes. In this case, it would be great Note A would be in edit mode as it is already opened in a pane.

Therefore, it would be great if there can be such an option in the configuration page for setting if one only wants the default view mode to work when opening it in a new pane or whenever clicking the note after viewing/editing another note.

**Comment by bwydoogh** [comment]
I agree; will add a setting for that.

**Comment by wenlzhang** [comment]
Thinking about this more, would it be possible to allow for a more flexible setting for this? Specifically, one can set this not just globally, but also for individual notes (through front matter, if possible). This is for the case where people may want to set certain notes in a default mode (preview or edit) regardless of opening them for the first time in a new pane or not.

For the global switch, the default option for this feature request can be off; it can be the same for individual notes, to be consistent with the name of this plugin. Then, one can set the global and local options with the following combinations (1 for on and 0 for off).
| Global, Local (Note A) | Note A Status | Notes B, C, D Status |
| ---------------------- | ------------- | -------------------- |
| 0, 0 (default)         | Off           | Off                  |
| 0, 1                   | On            | Off                  |
| 1, 0                   | On            | On                   |
| 1, 1                   | On            | On                   |

The combinations above are just a rough thought, though. As can be seen, there can be some confusions regarding which setting (global or local) should prioritize the other, and I am not certain if these combinations make sense from the programming point of view.

**Comment by bwydoogh** [comment]
Thanks for thinking about this so thoroughly.

About the last addition, however, I'm not entirely convinced it would have much added value. Personally, I don't want to make it too complex. That's why I would suggest to start with your original feature request: a setting that points out whether the note, when already opened, should be “forced” again in a certain mode (and if necessary change the mode to what the front matter key "says"). Will otherwise start with that already 😉 . If it should turn out that we need to go further with this then we can build on it.

**Comment by wenlzhang** [comment]
I agree that my last comment can be too complex.

> That's why I would suggest to start with your original feature request: a setting that points out whether the note, when already opened, should be “forced” again in a certain mode (and if necessary change the mode to what the front matter key "says").

I also think this can be a good start. Looking forward to the implementation. 😃

**Comment by bwydoogh** [comment]
Already had a first look at this; not yet found how to efficiently detect if a file was already open 🤔 .

**Comment by bwydoogh** [comment]
Released in `1.0.3`
