### ISSUE TITLE
What are there plans for submitting this plugin for official Obsidian plugin distribution

### ISSUE THREAD

**Issue by danieltomasz** [bwydoogh/obsidian-force-view-mode-of-note#5]
Really nice plugin! <3

Are there plans for submitting this plugin for official Obsidian plugin distribution?
I dont see the plugin as open pull request at Obsidian repository https://github.com/obsidianmd/obsidian-releases/pulls, but maybe I am missing something

Would be more convenient to have a posibility to install the plugin through Obsidian plugin distrubution, especially for people who have many vaults on different computers

**Comment by bwydoogh** [comment]
It is waiting for approval: https://github.com/obsidianmd/obsidian-releases/pull/411
