### ISSUE TITLE
Add a command for setting default view mode for all notes

### ISSUE THREAD

**Issue by wenlzhang** [bwydoogh/obsidian-force-view-mode-of-note#7]
While the current version supports setting view mode for individual notes, it can also be very useful to be able to set the default view mode for all notes. For example,

1. One may use query notes by using Dataview. When using this plugin, a table of notes can be displayed in preview mode. In such a case, when clicking a note link in the rendered table, the note would default to open in preview mode. However, one may want to edit those notes instead, e.g. when summarizing/organizing inbox notes. Therefore, it would be great to be able to set those notes to open in edit mode.
  - [blacksmithgu/obsidian-dataview: A complex query language implementation for the Obsidian note-taking tool.](https://github.com/blacksmithgu/obsidian-dataview)
2. One may open some query notes from a note in edit. In this case, the desired mode for those query notes may be in preview mode.

For my use case, the first one is very common. Therefore, it would be great to be able to add such a command to be able to temporarily make all notes to open in edit/preview mode, without needing to set for individual notes or go to the configuration pane.

**Comment by bwydoogh** [comment]
Hi.

> it would be great to be able to add such a command to be able to temporarily make all notes to open in edit/preview mode

I understand the idea, though I'm actually not tempted to implement this via this plug-in. This should actually be a feature of Obsidian (thus allowing you to change the configuration "default editor mode"). So I'll skip this one for now 🙂 .
